#!/usr/bin/env php
<?php

define('APP_VERSION', '1.2.1');

// installed via composer?
if (file_exists($a = __DIR__ . '/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use Camcima\MySqlDiff\Command\DiffCommand;
use Camcima\MySqlDiff\Command\MigrateCommand;
use Symfony\Component\Console\Application;

$application = new Application('PHP MySQL Diff', APP_VERSION);
$application->add(new MigrateCommand());
$application->add(new DiffCommand());
$application->run();
